version: '3.8'

services:
  forms-flow-web:
    container_name: forms-flow-web
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3000:8080"
    tty: true
  forms-flow-admin:
    container_name: forms-flow-admin
    build:
      context: ../admin/
      dockerfile: ../admin/Dockerfile
      args:
        - COMPONENT_NAME=admin
        - PORT=3001
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3001:3001"
    tty: true
  forms-flow-applications:
    container_name: forms-flow-applications
    build:
      context: ../applications/
      dockerfile: ../applications/Dockerfile
      args:
        - COMPONENT_NAME=applications
        - PORT=3002
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3002:3002"
    tty: true
  forms-flow-dashboards:
    container_name: forms-flow-dashboards
    build:
      context: ../dashboards/
      dockerfile: ../dashboards/Dockerfile
      args:
        - COMPONENT_NAME=dashboards
        - PORT=3005
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3005:3005"
    tty: true
  forms-flow-forms:
    container_name: forms-flow-forms
    build:
      context: ../forms/
      dockerfile: ../forms/Dockerfile
      args:
        - COMPONENT_NAME=forms
        - PORT=3003
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3003:3003"
    tty: true
  forms-flow-process:
    container_name: forms-flow-process
    build:
      context: ../process/
      dockerfile: ../process/Dockerfile
      args:
        - COMPONENT_NAME=process
        - PORT=3004
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3004:3004"
    tty: true
  forms-flow-tasks:
    container_name: forms-flow-tasks
    build:
      context: ../tasks/
      dockerfile: ../tasks/Dockerfile
      args:
        - COMPONENT_NAME=tasks
        - PORT=3006
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3006:3006"
    tty: true

  




  